version: "3"
services:
  mysql:
    image: mysql:8.0.32
    cap_add:
      - SYS_NICE
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      SPRING_PROFILES_ACTIVE: local
      MYSQL_ROOT_PASSWORD: 1597
      MYSQL_DATABASE: moida
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
