server:
  port: 8081

spring:
  datasource:
    url: ENC(RJxG2cp1957YBcZOascl8hTdUROmPZcR8s9nJaM5/OwNVCoIj9E/RnR+3lSGfxo2EZMWVcD4HsAZBgOKPdHKXNjULDvd+KvKKjfOhAG6Wlg+a/RAJbwDTCe+pe0KAEprQlImw1ypR8PAvNyd9BGByNJXmUJ+9hRrR3UBfPvhC6g=)
    username: ENC(dkSWwgPbVTSIF607/lEdpQ==)
    password: ENC(Yj3yX6sAVBOaFos921On3g==)

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/**.xml
