server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moida?&serverTimezone=Asia/Seoul&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: root
    password: 1597

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/**.xml
